var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/notes/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0x1hbim._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_11v-gj..js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_0qtlj82._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n00b86._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09xfqu6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_notes_error_tsx_0y8mkzd._.js")
R.c("server/chunks/ssr/app_notes_loading_tsx_0eel01v._.js")
R.c("server/chunks/ssr/_next-internal_server_app_notes_page_actions_0wivfyl.js")
R.m(38672)
module.exports=R.m(38672).exports
