name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
   
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and build 🔧
        run: |
          npm install
          npm run build
        env:
          NEXT_PUBLIC_NOTEHUB_TOKEN: ${{ secrets.NEXT_PUBLIC_NOTEHUB_TOKEN }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: out
          clean: true